export default {
    'FETCH_USERS':'rest/FETCH_USERS',
    'FETCH_USERS_COMPLETED': 'rest/FETCH_USERS_COMPLETED',
    'FETCH_USERS_FAILED': 'rest/FETCH_USERS_FAILED',

    'FETCH_USER_DETAILS_COMPLETED': 'rest/FETCH_USER_DETAILS_COMPLETED',
    'FETCH_USER_DETAILS_FAILED': 'rest/FETCH_USER_DETAILS_FAILED',
};